title: Flyte
description: Accelerate your ML and Data workflows to production.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.flyte.org" # the base hostname & protocol for your site, e.g. http://example.com

#Links within the site
documentation: "https://flyte.readthedocs.io/en/latest/"
getstarted: "https://flyte.readthedocs.io/en/latest/user/getting_started/index.html"
contribute: "https://flyte.readthedocs.io/en/latest/contributor/index.html"
learnmore: "https://flyte.readthedocs.io/en/latest/"
email: "users@flyte.org"
blog: "https://medium.com/flyte-org"
github: "https://github.com/flyteorg/flyte"
community: "https://docs.google.com/forms/d/e/1FAIpQLScWPJZncyL-bBCWbuQ9HWuMzA8-r2RJc__CSWJoAYUQADN-BQ/viewform"
twitter: "https://twitter.com/flyteorg"
stackoverflow: "https://stackoverflow.com/questions/tagged/flyte"

destination: _site

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
