title: Flyte by Lyft
description: A managed platform for executing distributed workflows at scale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kylewaynebenson.github.io/flyte" # the base hostname & protocol for your site, e.g. http://example.com

#Links within the site
documentation: "https://lyft.github.io/flyte/"
getstarted: "https://github.com/lyft/flyte"
contribute: "https://lyft.github.io/flyte/contributor/index.html"
learnmore: "https://lyft.github.io/flyte/"
email: "https://groups.google.com/d/forum/flyte-discuss"
blog: "https://medium.com/flyte-org"
github: "https://github.com/lyft/flyte"
community: "https://flyte-org.slack.com"
twitter: "https://twitter.com/flyteorg"

destination: dist

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
